# GitHub Personal Access Token
GITHUB_TOKEN = "ghp_ABCDEFGHIJKLMNOPQRSTUVWXYZabcdef12"

# AWS Access Key
AWS_ACCESS_KEY_ID = "AKIAIOSFODNN7EXAMPLE"
AWS_SECRET_ACCESS_KEY = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"

# Slack Bot Token
SLACK_TOKEN = "xoxb-123456789012-1234567890123-ABCDEFGHIJKLMNOPabcdefgh"
